services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\ConnectorMistral\ActionHandler\ImageToTextActionHandler:
        calls:
            - setDefaultMaxTokens: [ '%cr.connector_mistral.image_to_text.default_max_tokens%' ]
            - setDefaultTemperature: [ '%cr.connector_mistral.image_to_text.default_temperature%' ]
            - setDefaultModel: [ '%cr.connector_mistral.image_to_text.default_model%' ]
        tags:
            - { name: ibexa.ai.action.handler, priority: 100 }
            - { name: ibexa.ai.action.handler.image_to_text, priority: 100 }

    CodeRhapsodie\ConnectorMistral\ActionHandler\TextToTextActionHandler:
        calls:
            - setDefaultMaxTokens: [ '%cr.connector_mistral.text_to_text.default_max_tokens%' ]
            - setDefaultTemperature: [ '%cr.connector_mistral.text_to_text.default_temperature%' ]
            - setDefaultModel: [ '%cr.connector_mistral.text_to_text.default_model%' ]
        tags:
            - { name: ibexa.ai.action.handler, priority: 100 }
            - { name: ibexa.ai.action.handler.text_to_text, priority: 100 }
