services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\ConnectorMistral\ClientProvider:
      arguments:
        $clientClassname: '%code_rhapsodie.connector_mistral.client.classname%'

    CodeRhapsodie\Contracts\ConnectorMistral\ClientProviderInterface:
        '@CodeRhapsodie\ConnectorMistral\ClientProvider'
