services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\ConnectorMistral\ClientProvider: ~

    CodeRhapsodie\Contracts\ConnectorMistral\ClientProviderInterface:
        '@CodeRhapsodie\ConnectorMistral\ClientProvider'
