services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CodeRhapsodie\Bundle\ConnectorMistral\Installer\InstallerProvisioner:
        tags:
            -   name: ibexa.installer.provisioner.commerce
            -   name: ibexa.installer.provisioner.experience
            -   name: ibexa.installer.provisioner.headless

